# Generated by Django 4.2.26 on 2025-11-14 11:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_deal_invoice_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('call', 'Appel'), ('email', 'Email'), ('meeting', 'Réunion'), ('other', 'Autre')], max_length=20)),
                ('date_echeance', models.DateTimeField()),
                ('realise_le', models.DateTimeField(blank=True, null=True)),
                ('titre', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('priorite', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=20)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date_echeance'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_commission', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taux_commission', models.DecimalField(decimal_places=2, max_digits=5)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_facture', models.CharField(max_length=50, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, help_text='Montant HT de la facture', max_digits=10)),
                ('montant_ttc', models.DecimalField(decimal_places=2, help_text='Montant TTC de la facture', max_digits=10)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut_paiement', models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('cancelled', 'Annulée'), ('overdue', 'En retard')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_offre', models.CharField(max_length=255)),
                ('plan_commission', models.CharField(choices=[('one_shot', 'One-shot'), ('durable', 'Durable')], max_length=20)),
                ('taux_commission', models.DecimalField(decimal_places=2, help_text='Commission rate in percentage (e.g., 20.00 for 20%)', max_digits=5)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Offres',
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profil', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.CharField(blank=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Taux de commission par défaut', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('non_active', 'Non Active')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='deal',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='commercial',
        ),
        migrations.AddField(
            model_name='deal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='montant',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant estimé du deal', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='nom_deal',
            field=models.CharField(default='deal1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='nom_entreprise',
            field=models.CharField(default='e1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deal',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='remporte_le',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='type_deal',
            field=models.CharField(choices=[('one_shot', 'One-shot'), ('durable', 'Durable')], default='one_shot', max_length=20),
        ),
        migrations.AddField(
            model_name='deal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='company_name',
            field=models.CharField(default='C1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='contact_name',
            field=models.CharField(default='C', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leads_created', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='declared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='email',
            field=models.EmailField(default='Eml', max_length=255, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='lead',
            name='siret',
            field=models.CharField(blank=True, help_text='SIRET number (14 digits)', max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{14}$')]),
        ),
        migrations.AddField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En Cours'), ('converti', 'Converti'), ('perdu', 'Perdu')], default='nouveau', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('prospection', 'Prospection'), ('qualification', 'Qualification'), ('negociation', 'Négociation'), ('contrat', 'Contrat'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='prospection', max_length=20),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['stage'], name='myapp_deal_stage_8c3629_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['type_deal'], name='myapp_deal_type_de_c9adec_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['remporte_le'], name='myapp_deal_remport_0a7c50_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['status'], name='myapp_lead_status_356937_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['created_at'], name='myapp_lead_created_2fe26e_idx'),
        ),
        migrations.AddIndex(
            model_name='lead',
            index=models.Index(fields=['company_name'], name='myapp_lead_company_362a46_idx'),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='relation',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='relation',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relations', to='myapp.lead'),
        ),
        migrations.AddField(
            model_name='relation',
            name='offre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations', to='myapp.offre'),
        ),
        migrations.AddField(
            model_name='facture',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures_commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commission',
            name='deal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='myapp.deal'),
        ),
        migrations.AddField(
            model_name='action',
            name='commercial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions_commercial', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='myapp.lead'),
        ),
        migrations.AddField(
            model_name='deal',
            name='facture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal', to='myapp.facture'),
        ),
        migrations.AddField(
            model_name='deal',
            name='relation',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='myapp.relation'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['statut'], name='myapp_relat_statut_c33e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='relation',
            index=models.Index(fields=['commercial', 'statut'], name='myapp_relat_commerc_7ec804_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together={('lead', 'offre', 'commercial')},
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['statut_paiement'], name='myapp_factu_statut__3db607_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_facture'], name='myapp_factu_date_fa_98527a_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['date_echeance'], name='myapp_actio_date_ec_17926a_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['statut'], name='myapp_actio_statut_0b68f6_idx'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['commercial', 'date_echeance'], name='myapp_actio_commerc_230343_idx'),
        ),
    ]
