# Generated by Django 4.2.26 on 2025-11-21 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_action_commission_facture_offre_profil_relation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='commission_rate',
        ),
    ]
