# Generated by Django 4.2.26 on 2025-11-24 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_profil_commission_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='nom_entreprise',
        ),
        migrations.AddField(
            model_name='deal',
            name='date_paiment_client',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='date_paiment_commission',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offre',
            name='condition_commission_additionel',
            field=models.CharField(default='ras', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lead',
            name='email',
            field=models.EmailField(max_length=255, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='lead',
            name='siret',
            field=models.CharField(blank=True, help_text='SIRET number (9 digits)', max_length=14, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{194}$')]),
        ),
    ]
