# Generated by Django 4.2.26 on 2025-11-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_deal_nom_entreprise_deal_date_paiment_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='derniere_action',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
