# Generated by Django 4.2.26 on 2025-11-24 20:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_relation_derniere_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='montant_commission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='commission',
            name='taux_commission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='montant',
            field=models.IntegerField(blank=True, help_text='Montant estimé du deal', null=True),
        ),
        migrations.AlterField(
            model_name='deal',
            name='taux_commission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lead',
            name='siret',
            field=models.CharField(blank=True, help_text='SIRET number (9 digits)', max_length=9, null=True, validators=[django.core.validators.RegexValidator(regex='^\\d{9}$')]),
        ),
    ]
