# Generated by Django 4.2.26 on 2025-11-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_commission_montant_commission_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='relation',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='deal',
            name='taux_commission',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', False)), fields=('lead', 'offre', 'commercial'), name='unique_relation_per_lead'),
        ),
        migrations.AddConstraint(
            model_name='relation',
            constraint=models.UniqueConstraint(condition=models.Q(('lead__isnull', True)), fields=('offre', 'commercial'), name='unique_relation_without_lead'),
        ),
    ]
