# Generated by Django 4.2.26 on 2025-11-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_relation_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('prospection', 'Prospection'), ('negociation', 'Négociation'), ('gagne', 'Gagné'), ('perdu', 'Perdu')], default='prospection', max_length=20),
        ),
    ]
