# Generated by Django 4.2.26 on 2025-11-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_deal_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.DeleteModel(
            name='Commission',
        ),
    ]
